image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - dotnet build -c Release
    - dotnet run --project Cargu.Tests/Cargu.Tests.csproj -c Release -f netcoreapp2.0
    - dotnet run --project Cargu.Tests/Cargu.Tests.csproj -c Release -f net461

deploy_job:
  stage: deploy
  only:
    - master
    - release
  script:
    - ./ci.sh

  dependencies:
    - build_job
  